### PR TITLE
Refactored PowerDNS state for expandability and simplification

### LINKED ISSUE #5: Does not work out of the box
Including powerdns in the top.sls and running highstate results in it failing to render the configuration:

```
----------
ID: powerdns_config
Function: file.managed
Name: /etc/powerdns/pdns.conf
Result: False
Comment: Unable to manage file: Jinja error: argument of type 'StrictUndefined' is not iterable
Traceback (most recent call last):
File "/usr/lib/pymodules/python2.7/salt/utils/templates.py", line 261, in render_jinja_tmpl
output = jinja_env.from_string(tmplstr).render(**unicode_context)
File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 894, in render
return self.environment.handle_exception(exc_info, True)
File "<template>", line 11, in top-level template code
TypeError: argument of type 'StrictUndefined' is not iterable

; line 11

---
[...]
#################################
# allow-axfr-ips If enabled, restrict zonetransfers to originate from these
# IP addresses
#
# allow-axfr-ips=
{% if 'dns-supermaster' in grains['role'] %} <======================
allow-axfr-ips={{ pillar['networks']['dns-master']['ip'] }}
{% endif %}

#################################
# allow-recursion	List of netmasks that are allowed to recurse
[...]
---
Changes: 
```

### PR DESCRIPTION
**Pull request by kpostrup**
I have refactored the PowerDNS state for expandability and simplification.

I have added support for [PowerDNS package repository](https://repo.powerdns.com/) and simplified `pdns.conf` to write settings directly from Pillar. This adds flexibility as PowerDNS has changed config options between releases.

The formula will no longer attempt to create MySQL database, user or grants as this is outside the scope of this formula. Instead [MySQL formula](http://github.com/saltstack-formulas/mysql-formula) should be used. This also makes sense if the user has an existing database, residing on an external host.

I have tested this on Ubuntu 16.04 and prepared the formula for RedHat/CentOS support.

This also fixes #5

### CODE REVIEW

**Comment by gravyboat** [comment]
Hmm, this is a huge change that I'm going to need someone else to review. The lack of database creation adds additional work for the user (though I agree with your premise) and makes this formula backwards incompatible. @costibleotu could you please take a look since you've done most of the work on this?

**Comment by kpostrup** [comment]
@gravyboat I agree that it breaks backward compatibility, which of course is not ideal!

This is one of the older formulas, originally written before using maps and before the mysql-formula even existed, which explains why it includes MySQL user creation. It also requires the user to set up specific grains on minions for configuration.

I took the assumption that this formula was abandoned (no activity in the last 3 years). Except for open issue #5 which is 2+ years old.

**Comment by gravyboat** [comment]
@kpostrup For sure, I'm of the same made that this could definitely use some updates. If you don't hear from @costibleotu by tomorrow ping me and I'll merge it. I reviewed the changes this morning and I'm fine with them.

**Comment by kpostrup** [comment]
@gravyboat I have added some changes. Would you review them before we merge this?

To make sure that we are not loosing functionality, I have tested creation of the actual PowerDNS MySQL schema, by using mysql-formula, with the following pillar data as example:
```yaml
mysql:
  schema:
    powerdns:
      load: True
      source: salt://files/powerdns.mysql
```

The actual schema one wants to use, can depend on the PowerDNS version, and if you want to include DNSSEC or not. Due to the choice between multiple backends (MySQL, PostgreSQL, SQLite3, ODBC etc.) I think the actual MySQL schema should not necessarily be included in this formula.

**Comment by gravyboat** [comment]
Looks good to me on the changes. I'm going to merge this. If people have problems they can create an issue.

**Pull request merged**
