### PR TITLE
Add support for the sqlite backend, and for SUSE OSes

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by aboe76** [comment]
@tampakrap could you take a look at the #8 see if this overlaps?

**Comment by bentwire** [comment]
It does overlap a little.  I went a bit farther than #8 though and added DB initialization.  And state and execution modules for pdnsapi...

**Comment by aboe76** [comment]
@tampakrap could you please see if you can adjust and remove the sqlitebackend part, because it was already merged....

**Comment by tampakrap** [comment]
sure, I'll just remove it

**Comment by tampakrap** [comment]
@aboe76 done

**Comment by aboe76** [comment]
@tampakrap thanks.

**Pull request merged**
